"""
Vibe-Coding Detector — flags code patterns common in AI-generated output:

  • Over-permissive system calls (chmod 0o777, --allow-all, cors=*)
  • Hallucinated imports (curated list of fake stdlib paths LLMs invent)
  • AI-marker boilerplate (TODO placeholders, "example_function" names)
  • Missing error handling around network calls
  • Catch-all `except Exception: pass` adjacent to network calls

Returns Shadow-Stalker-compatible finding dicts so they flow through the
existing pipeline and Lead Warden taxonomy.
"""

from __future__ import annotations

import ast
import re
from typing import Iterable

# ── 1. Over-permissive call patterns (regex) ─────────────────────
_PERMISSIVE_PATTERNS: list[tuple[str, str, str]] = [
    (r"chmod\s*\(\s*[^,)]+,\s*0?o?777\s*\)", "chmod 0o777", "HIGH"),
    (r"chmod\s+777\b", "shell chmod 777", "HIGH"),
    (r"--allow-all\b", "--allow-all flag", "MEDIUM"),
    (r"cors\s*=\s*[\"']?\*[\"']?", "wildcard CORS", "MEDIUM"),
    (r"\ballow_origins\s*=\s*\[\s*[\"']\*[\"']\s*\]", "CORS allow_origins=['*']", "MEDIUM"),
    (r"verify\s*=\s*False\b", "TLS verify disabled", "HIGH"),
    (r"DEBUG\s*=\s*True\b", "DEBUG=True in source", "LOW"),
    (r"trust_remote_code\s*=\s*True", "trust_remote_code=True", "HIGH"),
]

# ── 2. Hallucinated/fake stdlib paths LLMs sometimes emit ────────
_FAKE_IMPORTS = {
    "langchain.utils.fake",
    "openai.experimental_unsafe",
    "anthropic.tools.shell",
    "transformers.unsafe",
    "torch.experimental.exec",
    "numpy.unsafe_eval",
    "fastapi.security.passthrough",
    "pydantic.unsafe_validate",
}

# ── 3. Boilerplate AI-marker strings ─────────────────────────────
_AI_MARKERS = [
    (r"#\s*TODO:\s*implement\b", "TODO: implement marker", "LOW"),
    (r"#\s*placeholder\b", "placeholder marker", "LOW"),
    (r"\bdef\s+example_function\s*\(", "example_function name", "LOW"),
    (r"\braise\s+NotImplementedError\s*\(", "NotImplementedError stub", "LOW"),
    (r"#\s*Generated by .* AI\b", "AI-generated banner", "LOW"),
    (r"#\s*your\s+(api|secret)\s+key\s+here", "credential placeholder", "MEDIUM"),
]


def _scan_regex(rules: Iterable[tuple[str, str, str]], source: str, filename: str,
                technique: str) -> list[dict]:
    out: list[dict] = []
    for pattern, label, severity in rules:
        for m in re.finditer(pattern, source, flags=re.IGNORECASE):
            line = source.count("\n", 0, m.start()) + 1
            out.append({
                "type": "vibe_smell",
                "technique": technique,
                "pattern": label,
                "line": line,
                "severity": severity,
                "description": f"Vibe-coding smell: {label}",
                "evidence": m.group(0)[:120],
                "filename": filename,
                "stage": "stage1",
            })
    return out


def _scan_imports(source: str, filename: str) -> list[dict]:
    out: list[dict] = []
    try:
        tree = ast.parse(source, filename=filename)
    except SyntaxError:
        return out
    for node in ast.walk(tree):
        names: list[str] = []
        if isinstance(node, ast.Import):
            names = [a.name for a in node.names]
        elif isinstance(node, ast.ImportFrom) and node.module:
            names = [node.module]
        for name in names:
            if name in _FAKE_IMPORTS or any(name.startswith(p + ".") for p in _FAKE_IMPORTS):
                out.append({
                    "type": "vibe_smell",
                    "technique": "hallucinated_import",
                    "pattern": name,
                    "line": getattr(node, "lineno", 0),
                    "severity": "HIGH",
                    "description": f"Hallucinated/non-existent import: '{name}' — common AI-generated mistake.",
                    "evidence": name,
                    "filename": filename,
                    "stage": "stage1",
                })
    return out


_NETWORK_CALL_RE = re.compile(
    r"\b(?:requests|httpx|urllib\.request|aiohttp\.[A-Za-z_]+)\.(?:get|post|put|delete|request|fetch)\s*\("
)


def _scan_network_no_handler(source: str, filename: str) -> list[dict]:
    out: list[dict] = []
    lines = source.splitlines()
    for i, line in enumerate(lines):
        if not _NETWORK_CALL_RE.search(line):
            continue
        # Look back up to 3 lines for try:; look forward 5 lines for except.
        window_back = "\n".join(lines[max(0, i - 3):i])
        window_fwd = "\n".join(lines[i + 1:i + 6])
        has_try = "try:" in window_back
        has_except = re.search(r"except\b", window_fwd) is not None
        if not (has_try and has_except):
            out.append({
                "type": "vibe_smell",
                "technique": "missing_error_handling",
                "pattern": "network_call_no_try",
                "line": i + 1,
                "severity": "MEDIUM",
                "description": "Network call without surrounding try/except — typical of AI-generated stubs.",
                "evidence": line.strip()[:120],
                "filename": filename,
                "stage": "stage1",
            })
        # Catch-all next to network call
        if has_except and re.search(r"except\s+Exception\s*:\s*\n\s*pass", window_fwd):
            out.append({
                "type": "vibe_smell",
                "technique": "swallowed_exception",
                "pattern": "except_pass_near_network",
                "line": i + 1,
                "severity": "MEDIUM",
                "description": "Bare `except Exception: pass` near a network call — silent failure mode.",
                "evidence": line.strip()[:120],
                "filename": filename,
                "stage": "stage1",
            })
    return out


def detect_vibe_smells(source: str, filename: str = "unknown") -> dict:
    """Aggregate all vibe-coding heuristics. Returns Shadow-Stalker shape."""
    findings: list[dict] = []
    findings.extend(_scan_regex(_PERMISSIVE_PATTERNS, source, filename, "over_permissive"))
    findings.extend(_scan_regex(_AI_MARKERS, source, filename, "ai_marker"))
    findings.extend(_scan_imports(source, filename))
    findings.extend(_scan_network_no_handler(source, filename))
    return {
        "filename": filename,
        "findings": findings,
        "count": len(findings),
    }
